// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TedBank.Models;

namespace TedBank.Migrations
{
    [DbContext(typeof(TedBankContext))]
    partial class TedBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TedBank.Models.TedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Speaker");

                    b.Property<string>("Title");

                    b.Property<string>("Topic");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("TedItem");
                });
#pragma warning restore 612, 618
        }
    }
}
